---
name: "Setup graudit"
author: Yevhen Fabizhevskyi
description: "This action installs graudit CLI tool."
branding:
  icon: terminal
  color: gray-dark
inputs:
  version:
    description: "graudit version."
    required: false
    default: "3.7"
runs:
  using: "composite"
  steps:
    - name: Collect info
      id: info
      run: |
        graudit_installed=$(if command -v graudit >/dev/null 2>&1; then echo true; else echo false; fi)
        echo "graudit-installed=${graudit_installed}" >> "$GITHUB_OUTPUT"
        graudit_path="${GITHUB_WORKSPACE}/graudit"
        mkdir -p "${graudit_path}"
        echo "graudit-path=${graudit_path}" >> "$GITHUB_OUTPUT"
      shell: sh
    - name: Download graudit
      if: ${{ steps.info.outputs.graudit-installed == 'false' }}
      uses: actions/checkout@v4
      with:
        repository: wireghoul/graudit
        ref: v${{ inputs.version }}
        fetch-depth: 1
        path: graudit
    - name: Install graudit
      if: ${{ steps.info.outputs.graudit-installed == 'false' }}
      run: |
        echo "${{ steps.info.outputs.graudit-path }}" >> "$GITHUB_PATH"
        echo "GRDIR=${{ steps.info.outputs.graudit-path }}/signatures" >> "$GITHUB_ENV"
      shell: sh
